"""Build source-backed input contracts for RateWall-oriented tdcsim runs.

The builder deliberately separates exact public source objects from constrained
allocations. MSPD supplies security-level marketable Treasury cohorts; public
holder-by-CUSIP data are not available, so holder rows are generated by applying
source-backed aggregate holder constraints to the MSPD cohort ladder.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlencode
from urllib.request import Request, urlopen
from zipfile import ZipFile

import pandas as pd
import yaml


FISCALDATA_BASE = "https://api.fiscaldata.treasury.gov/services/api/fiscal_service"
TREASURY_CURVE_XML = "https://home.treasury.gov/resource-center/data-chart-center/interest-rates/pages/xml?data=daily_treasury_yield_curve"
RATEWALL_CLAIM_BOUNDARY = "tdcsim_ratewall_source_backed_input_contract_not_evidence_mode"
TENORS = [0.25, 0.5, 1.0, 2.0, 5.0, 10.0, 20.0, 30.0]
TDCSIM_HOLDERS = ["Banks", "CB", "Foreign", "Private"]
PREFERENCE_CATEGORIES = ["bills", "notes", "bonds", "tips", "frn"]
Z1_LOOKBACK_QUARTERS = 8
Z1_SHRINKAGE_K_QUARTERS = 8.0
Z1_POSITIVE_ABSORPTION_FLOOR_BN_SAAR = 25.0
Z1_FLOOR_MEDIAN_MULTIPLIER = 0.10
PRIMARY_MARKET_LOOKBACK_QUARTERS = 8
PRIMARY_MARKET_OVERLAY_WEIGHT = 0.20
SCENARIO_SHIFT_LAMBDA_GRID = [0.25, 0.50, 0.75, 1.00]
SCENARIO_SHIFT_LAMBDA_DEFAULT = 0.50
RATE_SCENARIOS = {
    "cbo_shape_preserving_baseline": {
        "short_shift": 0.0,
        "long_shift": 0.0,
        "central_default_eligible": "true",
        "sensitivity_only": "false",
        "source_status": "source_backed_dynamic_curve_surface_not_flat_rate",
    },
    "higher_for_longer_sensitivity": {
        "short_shift": 0.0075,
        "long_shift": 0.0075,
        "central_default_eligible": "false",
        "sensitivity_only": "true",
        "source_status": "transparent_parallel_stress_around_source_backed_cbo_curve",
    },
    "rapid_easing_sensitivity": {
        "short_shift": -0.0075,
        "long_shift": -0.0075,
        "central_default_eligible": "false",
        "sensitivity_only": "true",
        "source_status": "transparent_parallel_stress_around_source_backed_cbo_curve",
    },
    "bear_steepener_sensitivity": {
        "short_shift": 0.0025,
        "long_shift": 0.0100,
        "central_default_eligible": "false",
        "sensitivity_only": "true",
        "source_status": "transparent_curve_shape_stress_around_source_backed_cbo_curve",
    },
    "bull_flattener_sensitivity": {
        "short_shift": -0.0100,
        "long_shift": -0.0025,
        "central_default_eligible": "false",
        "sensitivity_only": "true",
        "source_status": "transparent_curve_shape_stress_around_source_backed_cbo_curve",
    },
}
SCENARIO_CURVE_MAP = {
    "current_mix_baseline": "cbo_shape_preserving_baseline",
    "domestic_nonbank_absorption_shift": "cbo_shape_preserving_baseline",
    "reserve_user_absorption_shift": "cbo_shape_preserving_baseline",
    "current_mix_higher_for_longer": "higher_for_longer_sensitivity",
    "current_mix_rapid_easing": "rapid_easing_sensitivity",
    "domestic_nonbank_absorption_shift_higher_for_longer": "higher_for_longer_sensitivity",
    "domestic_nonbank_absorption_shift_rapid_easing": "rapid_easing_sensitivity",
    "reserve_user_absorption_shift_higher_for_longer": "higher_for_longer_sensitivity",
    "reserve_user_absorption_shift_rapid_easing": "rapid_easing_sensitivity",
    "current_mix_bear_steepener": "bear_steepener_sensitivity",
    "current_mix_bull_flattener": "bull_flattener_sensitivity",
}


def _request_json(url: str) -> dict:
    with urlopen(Request(url, headers={"User-Agent": "tdcsim-ratewall-source-builder"}), timeout=60) as response:
        return json.loads(response.read().decode("utf-8"))


def _fiscaldata_url(path: str, **params: str | int) -> str:
    return f"{FISCALDATA_BASE}/{path}?{urlencode(params)}"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _safe_float(value, default: float = 0.0) -> float:
    if value in {None, "", "null"}:
        return default
    try:
        if pd.isna(value):
            return default
    except TypeError:
        pass
    try:
        return float(str(value).replace(",", ""))
    except ValueError:
        return default


def _quarter_label(ts) -> str:
    stamp = pd.to_datetime(ts)
    return f"{stamp.year}Q{stamp.quarter}"


def _ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def _latest_record_date(endpoint: str) -> str:
    payload = _request_json(
        _fiscaldata_url(
            endpoint,
            sort="-record_date",
            **{"page[size]": 1, "format": "json"},
        )
    )
    return payload["data"][0]["record_date"]


def _fetch_fiscaldata_rows(endpoint: str, *, record_date: str, page_size: int = 10000) -> list[dict]:
    payload = _request_json(
        _fiscaldata_url(
            endpoint,
            filter=f"record_date:eq:{record_date}",
            **{"page[size]": page_size, "format": "json"},
        )
    )
    return list(payload.get("data", []))


def _security_type(class_desc: str) -> str | None:
    label = class_desc.lower()
    if "bill" in label:
        return "Fixed"
    if "floating" in label or "frn" in label:
        return "FRN"
    if "inflation-protected" in label or "tips" in label:
        return "TIPS"
    if "note" in label or "bond" in label:
        return "Fixed"
    return None


def _maturity_category(class_desc: str, original_maturity: float) -> str | None:
    label = class_desc.lower()
    if "bill" in label or original_maturity <= 1.0 + 1e-9:
        return "bills"
    if "note" in label or original_maturity <= 10.0 + 1e-9:
        return "notes"
    if "bond" in label:
        return "bonds"
    return None


def _class_key(class_desc: str) -> str | None:
    label = class_desc.lower()
    if "bill" in label:
        return "Bills"
    if "floating" in label or "frn" in label:
        return "Floating Rate Notes"
    if "inflation-protected" in label or "tips" in label:
        return "Treasury Inflation-Protected Securities"
    if "note" in label:
        return "Notes"
    if "bond" in label:
        return "Bonds"
    return None


def _load_stock_holder_shares(tsyparty_z1_path: Path) -> dict[str, float]:
    frame = pd.read_csv(tsyparty_z1_path)
    frame["date"] = pd.to_datetime(frame["date"])
    row = frame.sort_values("date").iloc[-1]
    private_cols = [
        "dealers",
        "households_residual",
        "insurers",
        "money_market_funds",
        "mutual_funds_etfs",
        "nonfinancial_corporates",
        "other_financial",
        "pensions",
        "state_local_governments",
    ]
    raw = {
        "Banks": _safe_float(row.get("banks")),
        "CB": _safe_float(row.get("fed")),
        "Foreign": _safe_float(row.get("foreigners_official")),
        "Private": sum(_safe_float(row.get(col)) for col in private_cols),
    }
    total = sum(raw.values())
    if total <= 0:
        raise ValueError(f"No positive holder stock shares in {tsyparty_z1_path}")
    return {holder: value / total for holder, value in raw.items()}


def _normalize_holder_shares(raw: dict[str, float]) -> dict[str, float]:
    clipped = {holder: max(0.0, float(raw.get(holder, 0.0))) for holder in TDCSIM_HOLDERS}
    total = sum(clipped.values())
    if total <= 0:
        return {holder: 1.0 / len(TDCSIM_HOLDERS) for holder in TDCSIM_HOLDERS}
    return {holder: value / total for holder, value in clipped.items()}


def _blend_shares(
    left: dict[str, float],
    right: dict[str, float],
    *,
    right_weight: float,
) -> dict[str, float]:
    return _normalize_holder_shares(
        {
            holder: (1.0 - right_weight) * left.get(holder, 0.0)
            + right_weight * right.get(holder, 0.0)
            for holder in TDCSIM_HOLDERS
        }
    )


def _default_holder_absorption_calibration() -> dict[str, float | list[float]]:
    return {
        "scenario_shift_lambda_grid": list(SCENARIO_SHIFT_LAMBDA_GRID),
        "scenario_shift_lambda_default": SCENARIO_SHIFT_LAMBDA_DEFAULT,
    }


def _load_holder_absorption_calibration(config_path: Path) -> dict[str, float | list[float]]:
    defaults = _default_holder_absorption_calibration()
    if not config_path.exists():
        return defaults
    loaded = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    section = loaded.get("holder_absorption_calibration", {})
    if not isinstance(section, dict):
        return defaults
    grid_raw = section.get("scenario_shift_lambda_grid", defaults["scenario_shift_lambda_grid"])
    if not isinstance(grid_raw, list) or not grid_raw:
        grid = list(SCENARIO_SHIFT_LAMBDA_GRID)
    else:
        grid = [float(value) for value in grid_raw]
    return {
        "scenario_shift_lambda_grid": grid,
        "scenario_shift_lambda_default": _safe_float(
            section.get("scenario_shift_lambda_default"),
            float(defaults["scenario_shift_lambda_default"]),
        ),
    }


def _load_tdcmix_targets(tdcmix_prior_path: Path) -> dict[str, dict[str, float]]:
    frame = pd.read_csv(tdcmix_prior_path)
    rows = {str(row["bucket"]): row for _, row in frame.iterrows()}

    def collapse(value_field: str) -> dict[str, float]:
        raw = {
            "CB": _safe_float(rows.get("fed", {}).get(value_field)),
            "Banks": _safe_float(rows.get("banks", {}).get(value_field)),
            "Foreign": _safe_float(rows.get("row", {}).get(value_field)),
            "Private": _safe_float(rows.get("domestic_nonbank", {}).get(value_field))
            + _safe_float(rows.get("mmf", {}).get(value_field)),
        }
        out = _normalize_holder_shares(raw)
        if sum(out.values()) <= 0:
            raise ValueError(f"No positive absorption priors in {tdcmix_prior_path}")
        return out

    baseline = collapse("default_prior_value")
    du_heavy = collapse("upper_prior_value")
    ru_raw = {
        "CB": _safe_float(rows.get("fed", {}).get("upper_prior_value")),
        "Banks": _safe_float(rows.get("banks", {}).get("upper_prior_value")),
        "Foreign": _safe_float(rows.get("row", {}).get("upper_prior_value")),
        "Private": _safe_float(rows.get("domestic_nonbank", {}).get("lower_prior_value"))
        + _safe_float(rows.get("mmf", {}).get("lower_prior_value")),
    }
    ru_heavy = _normalize_holder_shares(ru_raw)
    return {
        "current_mix_baseline": baseline,
        "domestic_nonbank_absorption_shift": du_heavy,
        "reserve_user_absorption_shift": ru_heavy,
    }


def _latest_z1_absorption_shares(z1_absorption_path: Path) -> tuple[dict[str, float] | None, float]:
    if not z1_absorption_path.exists():
        return None, 0.0
    frame = pd.read_csv(z1_absorption_path)
    if "quarter" not in frame.columns:
        return None, 0.0
    required = [
        "positive_absorption_total",
        "pos_abs_share_fed",
        "pos_abs_share_banks",
        "pos_abs_share_dealer_bridge",
        "pos_abs_share_row",
        "pos_abs_share_mmf",
        "pos_abs_share_domestic_nonbank",
    ]
    if not set(required) <= set(frame.columns):
        return None, 0.0
    frame["quarter_date"] = pd.to_datetime(frame["quarter"], errors="coerce")
    for column in required:
        frame[column] = pd.to_numeric(frame[column], errors="coerce")
    frame = (
        frame.dropna(subset=["quarter_date"])
        .dropna(subset=required)
        .sort_values("quarter_date")
        .tail(Z1_LOOKBACK_QUARTERS)
    )
    if frame.empty:
        return None, 0.0
    core_share = (
        frame["pos_abs_share_fed"]
        + frame["pos_abs_share_banks"]
        + frame["pos_abs_share_row"]
        + frame["pos_abs_share_mmf"]
        + frame["pos_abs_share_domestic_nonbank"]
    )
    eff_q = frame["positive_absorption_total"].clip(lower=0.0) * core_share.clip(lower=0.0, upper=1.0)
    positive_eff = eff_q[eff_q > 0.0]
    if positive_eff.empty:
        return None, 0.0
    floor = max(
        Z1_POSITIVE_ABSORPTION_FLOOR_BN_SAAR,
        Z1_FLOOR_MEDIAN_MULTIPLIER * float(positive_eff.median()),
    )
    quarter_credit = (eff_q / floor).clip(lower=0.0, upper=1.0)
    n_eff = float(quarter_credit.sum())
    if n_eff <= 0.0:
        return None, 0.0

    weighted = {holder: 0.0 for holder in TDCSIM_HOLDERS}
    for idx, row in frame.iterrows():
        credit = float(quarter_credit.loc[idx])
        if credit <= 0.0:
            continue
        shares = _normalize_holder_shares(
            {
                "CB": _safe_float(row["pos_abs_share_fed"]),
                "Banks": _safe_float(row["pos_abs_share_banks"]),
                "Foreign": _safe_float(row["pos_abs_share_row"]),
                "Private": _safe_float(row["pos_abs_share_domestic_nonbank"])
                + _safe_float(row["pos_abs_share_mmf"]),
            }
        )
        for holder in TDCSIM_HOLDERS:
            weighted[holder] += credit * shares[holder]
    return _normalize_holder_shares({holder: value / n_eff for holder, value in weighted.items()}), n_eff


def _latest_primary_market_instrument_shares(
    path: Path,
    *,
    baseline_scalar: dict[str, float],
) -> dict[str, float] | None:
    if not path.exists():
        return None
    frame = pd.read_csv(path)
    required = {"date", "buyer_class", "share"}
    if not required <= set(frame.columns):
        return None
    frame["date"] = pd.to_datetime(frame["date"], errors="coerce")
    frame = frame.dropna(subset=["date"]).sort_values("date")
    recent_dates = sorted(frame["date"].dropna().unique())[-PRIMARY_MARKET_LOOKBACK_QUARTERS:]
    frame = frame[frame["date"].isin(recent_dates)]
    if frame.empty:
        return None
    grouped = frame.groupby("buyer_class")["share"].mean()
    dealer_bridge_share = float(grouped.get("dealers", 0.0))
    raw = {
        "Banks": dealer_bridge_share * baseline_scalar.get("Banks", 0.0),
        "CB": float(grouped.get("fed", 0.0)) + dealer_bridge_share * baseline_scalar.get("CB", 0.0),
        "Foreign": float(grouped.get("foreign_official", 0.0))
        + dealer_bridge_share * baseline_scalar.get("Foreign", 0.0),
        "Private": dealer_bridge_share * baseline_scalar.get("Private", 0.0),
    }
    return _normalize_holder_shares(raw)


def _load_absorption_scenarios(
    tdcmix_prior_path: Path,
    *,
    z1_absorption_path: Path,
    bills_primary_path: Path,
    coupons_primary_path: Path,
    holder_absorption_calibration: dict[str, float | list[float]] | None = None,
) -> tuple[dict[str, dict[str, dict[str, float]]], dict[str, str]]:
    calibration = holder_absorption_calibration or _default_holder_absorption_calibration()
    scenario_shift_lambda_default = float(calibration["scenario_shift_lambda_default"])
    scenario_shift_lambda_grid = [float(value) for value in calibration["scenario_shift_lambda_grid"]]
    tdcmix_targets = _load_tdcmix_targets(tdcmix_prior_path)
    z1_recent, z1_n_eff = _latest_z1_absorption_shares(z1_absorption_path)
    z1_weight = z1_n_eff / (z1_n_eff + Z1_SHRINKAGE_K_QUARTERS) if z1_n_eff > 0.0 else 0.0
    baseline_scalar = tdcmix_targets["current_mix_baseline"]
    if z1_recent is not None:
        baseline_scalar = _blend_shares(baseline_scalar, z1_recent, right_weight=z1_weight)

    bills_primary = _latest_primary_market_instrument_shares(
        bills_primary_path,
        baseline_scalar=baseline_scalar,
    )
    coupons_primary = _latest_primary_market_instrument_shares(
        coupons_primary_path,
        baseline_scalar=baseline_scalar,
    )
    baseline_by_category: dict[str, dict[str, float]] = {}
    for category in PREFERENCE_CATEGORIES:
        instrument_prior = bills_primary if category == "bills" else coupons_primary
        shares = baseline_scalar
        if instrument_prior is not None:
            shares = _blend_shares(shares, instrument_prior, right_weight=PRIMARY_MARKET_OVERLAY_WEIGHT)
        baseline_by_category[category] = shares

    scenarios: dict[str, dict[str, dict[str, float]]] = {
        "current_mix_baseline": baseline_by_category,
        "current_mix_higher_for_longer": baseline_by_category,
        "current_mix_rapid_easing": baseline_by_category,
        "current_mix_bear_steepener": baseline_by_category,
        "current_mix_bull_flattener": baseline_by_category,
    }
    holder_shift_specs = [
        ("domestic_nonbank_absorption_shift", "domestic_nonbank_absorption_shift"),
        (
            "domestic_nonbank_absorption_shift_higher_for_longer",
            "domestic_nonbank_absorption_shift",
        ),
        (
            "domestic_nonbank_absorption_shift_rapid_easing",
            "domestic_nonbank_absorption_shift",
        ),
        ("reserve_user_absorption_shift", "reserve_user_absorption_shift"),
        (
            "reserve_user_absorption_shift_higher_for_longer",
            "reserve_user_absorption_shift",
        ),
        (
            "reserve_user_absorption_shift_rapid_easing",
            "reserve_user_absorption_shift",
        ),
    ]
    for scenario_id, target_key in holder_shift_specs:
        target = tdcmix_targets[target_key]
        scenarios[scenario_id] = {
            category: _blend_shares(shares, target, right_weight=scenario_shift_lambda_default)
            for category, shares in baseline_by_category.items()
        }

    metadata = {
        "baseline_sources": (
            "tdcmix_prior_contract"
            + (";z1_exact_recent_positive_absorption" if z1_recent is not None else "")
            + (";primary_market_instrument_buyer_composition" if bills_primary or coupons_primary else "")
        ),
        "dealer_bridge_mapping": "dealer_bridge_redistributed_by_pre_overlay_baseline_not_mapped_to_banks",
        "z1_effective_quarters_n_eff": f"{z1_n_eff:.12f}",
        "z1_shrinkage_weight": f"{z1_weight:.12f}",
        "z1_shrinkage_k_quarters": f"{Z1_SHRINKAGE_K_QUARTERS:.1f}",
        "primary_market_overlay_weight": f"{PRIMARY_MARKET_OVERLAY_WEIGHT:.2f}",
        "primary_market_overlay_coverage": (
            "low_coverage_only_dealers_fed_foreign_official_share_weighted"
            if bills_primary or coupons_primary
            else "not_available"
        ),
        "scenario_shift_lambda_default": f"{scenario_shift_lambda_default:.2f}",
        "scenario_shift_lambda_grid": ",".join(f"{value:.2f}" for value in scenario_shift_lambda_grid),
        "tic_foreign_cross_check_status": "DEFERRED_new_plumbing_QA_only_not_blocking_blend_weight_grounding",
    }
    return scenarios, metadata


def build_initial_portfolio(
    output_path: Path,
    *,
    tsyparty_z1_path: Path,
) -> tuple[pd.DataFrame, dict]:
    latest_date = _latest_record_date("v1/debt/mspd/mspd_table_1")
    table1 = _fetch_fiscaldata_rows("v1/debt/mspd/mspd_table_1", record_date=latest_date)
    table3 = _fetch_fiscaldata_rows("v1/debt/mspd/mspd_table_3_market", record_date=latest_date)
    targets = {
        row["security_class_desc"]: _safe_float(row.get("debt_held_public_mil_amt"))
        for row in table1
        if row.get("security_type_desc") == "Marketable"
    }
    holder_shares = _load_stock_holder_shares(tsyparty_z1_path)

    candidate_rows: list[dict] = []
    for row in table3:
        class_desc = str(row.get("security_class1_desc", ""))
        class_key = _class_key(class_desc)
        sec_type = _security_type(class_desc)
        if not class_key or not sec_type or class_desc == "Total Marketable":
            continue
        outstanding = _safe_float(row.get("outstanding_amt"), math.nan)
        if not math.isfinite(outstanding) or outstanding <= 0:
            continue
        issue_date = pd.to_datetime(row.get("issue_date"), errors="coerce")
        maturity_date = pd.to_datetime(row.get("maturity_date"), errors="coerce")
        if pd.isna(issue_date) or pd.isna(maturity_date):
            continue
        original_maturity = max(0.01, (maturity_date - issue_date).days / 365.25)
        candidate_rows.append(
            {
                "source_row": row,
                "class_key": class_key,
                "security_type": sec_type,
                "outstanding": outstanding,
                "issue_date": issue_date,
                "maturity_date": maturity_date,
                "original_maturity_years": original_maturity,
            }
        )

    raw_totals: dict[str, float] = {}
    for item in candidate_rows:
        raw_totals[item["class_key"]] = raw_totals.get(item["class_key"], 0.0) + item["outstanding"]

    output_rows: list[dict] = []
    bond_id = 1
    for item in candidate_rows:
        target_total = targets.get(item["class_key"], 0.0)
        raw_total = raw_totals.get(item["class_key"], 0.0)
        if target_total <= 0 or raw_total <= 0:
            continue
        class_scale = target_total / raw_total
        source_row = item["source_row"]
        class_desc = str(source_row.get("security_class1_desc", ""))
        cusip = str(source_row.get("security_class2_desc", "")).strip()
        coupon_rate = _safe_float(source_row.get("interest_rate_pct")) / 100.0
        issue_yield = _safe_float(source_row.get("yield_pct"), coupon_rate * 100.0) / 100.0
        maturity_years = item["original_maturity_years"]
        maturity_category = _maturity_category(class_desc, maturity_years)
        is_bill = maturity_category == "bills" and coupon_rate <= 1e-12
        price_ratio = 1.0
        if is_bill:
            day_count = max(1.0, (item["maturity_date"] - item["issue_date"]).days)
            price_ratio = max(0.75, min(1.0, 1.0 - issue_yield * day_count / 360.0))
        # MSPD amount fields are reported in millions of dollars. TDCSim and
        # RateWall contract columns use billions, so convert before writing the
        # cohort ladder consumed by the simulator.
        total_face = item["outstanding"] * class_scale / 1000.0
        for holder, share in holder_shares.items():
            face_value = total_face * share
            if face_value <= 1e-9:
                continue
            original_principal = face_value if item["security_type"] == "TIPS" else 0.0
            output_rows.append(
                {
                    "BondID": bond_id,
                    "SecurityType": item["security_type"],
                    "IssueDate": item["issue_date"].date().isoformat(),
                    "MaturityDate": item["maturity_date"].date().isoformat(),
                    "OriginalMaturityYears": f"{maturity_years:.8f}",
                    "FaceValue": f"{face_value:.12f}",
                    "CouponRate": f"{coupon_rate:.12f}",
                    "HolderType": holder,
                    "Status": "Active",
                    "MaturityCategory": maturity_category or "",
                    "OriginalPrincipal": f"{original_principal:.12f}",
                    "AdjustedPrincipal": f"{original_principal:.12f}",
                    "ReferenceCPI_Issue": "100.0" if item["security_type"] == "TIPS" else "0.0",
                    "IndexRatio": "1.0" if item["security_type"] == "TIPS" else "0.0",
                    "FixedSpread": "0.0005" if item["security_type"] == "FRN" else "0.0",
                    "AccruedInterest_FRN": "0.0",
                    "BenchmarkRate_FRN": f"{issue_yield:.12f}" if item["security_type"] == "FRN" else "0.0",
                    "LastAccrualDate": item["issue_date"].date().isoformat() if item["security_type"] == "FRN" else "",
                    "IssuePriceRatio": f"{price_ratio:.12f}",
                    "IssueProceeds": f"{face_value * price_ratio:.12f}",
                    "IssueYieldAtIssue": f"{issue_yield:.12f}",
                    "TimeToMaturity": "",
                    "DiscountYield": "",
                    "CleanPrice": "",
                    "AccruedInterest": "",
                    "DirtyValue": "",
                    "DirtyPriceRatio": "",
                    "cohort_id": f"mspd_{latest_date}_{cusip}_{bond_id}",
                    "cusip_or_synthetic_id": cusip,
                    "issue_proceeds_bil": f"{face_value * price_ratio:.12f}",
                    "face_value_bil": f"{face_value:.12f}",
                    "adjusted_principal_bil": f"{original_principal:.12f}",
                    "holder_bucket": holder,
                    "ratewall_perimeter": "DU" if holder == "Private" else "RU",
                    "source_family": "fiscaldata_mspd_table_3_market;tsyparty_z1_holder_constraints",
                    "source_key": f"{latest_date}:{class_desc}:{cusip}",
                    "observability_tier": "security_cohort_total_with_constrained_holder_allocation",
                    "central_default_eligible": "true",
                    "sensitivity_only": "false",
                    "source_status": (
                        "mspd_million_amounts_scaled_to_table1_class_total_and_converted_to_bil;"
                        "holder_split_from_latest_z1_aggregate_not_cusip_holder_evidence;"
                        "cusip_by_holder_public_source_unavailable"
                    ),
                    "claim_boundary": RATEWALL_CLAIM_BOUNDARY,
                }
            )
            bond_id += 1

    frame = pd.DataFrame(output_rows)
    frame.to_csv(output_path, index=False)
    metadata = {
        "mspd_record_date": latest_date,
        "rows": len(frame),
        "holder_stock_share_source": str(tsyparty_z1_path),
        "source_url_table_1": "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/debt/mspd/mspd_table_1",
        "source_url_table_3_market": "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/debt/mspd/mspd_table_3_market",
    }
    return frame, metadata


def _read_xlsx(path: Path) -> dict[str, list[list[str]]]:
    main_ns = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
    rel_ns = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
    pkg_rel_ns = "http://schemas.openxmlformats.org/package/2006/relationships"
    with ZipFile(path) as archive:
        shared_strings: list[str] = []
        if "xl/sharedStrings.xml" in archive.namelist():
            root = ET.fromstring(archive.read("xl/sharedStrings.xml"))
            for item in root.findall(f"{{{main_ns}}}si"):
                shared_strings.append(_clean("".join(node.text or "" for node in item.iter(f"{{{main_ns}}}t"))))
        workbook = ET.fromstring(archive.read("xl/workbook.xml"))
        rels = ET.fromstring(archive.read("xl/_rels/workbook.xml.rels"))
        rel_targets = {
            rel.attrib["Id"]: rel.attrib["Target"]
            for rel in rels.findall(f"{{{pkg_rel_ns}}}Relationship")
        }
        sheets: dict[str, list[list[str]]] = {}
        for sheet in workbook.findall(f".//{{{main_ns}}}sheet"):
            name = sheet.attrib["name"]
            rel_id = sheet.attrib[f"{{{rel_ns}}}id"]
            target = rel_targets[rel_id].lstrip("/")
            if not target.startswith("xl/"):
                target = f"xl/{target}"
            sheet_root = ET.fromstring(archive.read(target))
            rows: list[list[str]] = []
            for row_node in sheet_root.findall(f".//{{{main_ns}}}row"):
                values: dict[int, str] = {}
                max_col = -1
                for cell in row_node.findall(f"{{{main_ns}}}c"):
                    col_idx = _cell_col_index(cell.attrib.get("r", ""))
                    if col_idx < 0:
                        continue
                    values[col_idx] = _cell_value(cell, shared_strings, main_ns)
                    max_col = max(max_col, col_idx)
                rows.append([values.get(idx, "") for idx in range(max_col + 1)])
            sheets[name] = rows
    return sheets


def _cell_col_index(cell_ref: str) -> int:
    match = re.match(r"([A-Z]+)", cell_ref)
    if not match:
        return -1
    col_idx = 0
    for char in match.group(1):
        col_idx = col_idx * 26 + (ord(char) - ord("A") + 1)
    return col_idx - 1


def _cell_value(cell: ET.Element, shared_strings: list[str], main_ns: str) -> str:
    cell_type = cell.attrib.get("t", "")
    if cell_type == "inlineStr":
        return _clean("".join(node.text or "" for node in cell.iter(f"{{{main_ns}}}t")))
    value_node = cell.find(f"{{{main_ns}}}v")
    if value_node is None or value_node.text is None:
        return ""
    raw = value_node.text.strip()
    if cell_type == "s":
        try:
            return shared_strings[int(raw)]
        except (IndexError, ValueError):
            return raw
    return _clean(raw)


def _clean(value: str) -> str:
    return re.sub(r"\s+", " ", str(value)).strip()


def _cbo_budget_values(path: Path) -> dict[int, dict[str, float]]:
    workbook = _read_xlsx(path)
    rows = workbook["Table 1-1"]
    year_cols = _year_cols(rows)
    values: dict[int, dict[str, float]] = {}
    section = ""
    for row in rows:
        label = _clean(row[0] if row else "").lower()
        joined = _clean(" ".join(row)).lower()
        if "in billions of dollars" in joined:
            section = "billions"
            continue
        if "as a percentage of gdp" in joined:
            section = "percent_of_gdp"
            continue
        if section != "billions":
            continue
        metric = None
        if label == "net interest":
            metric = "net_interest_bil"
        elif label == "total deficit (-)":
            metric = "deficit_bil"
        elif label == "debt held by the public":
            metric = "debt_held_public_bil"
        if metric is None:
            continue
        for col_idx, year in year_cols.items():
            if col_idx >= len(row) or not row[col_idx]:
                continue
            values.setdefault(int(year), {})[metric] = _safe_float(row[col_idx])
    return values


def _cbo_rate_values(path: Path) -> dict[int, dict[str, float]]:
    workbook = _read_xlsx(path)
    rows = workbook["Table 2-1"]
    header = rows[6]
    year_cols = {
        idx: value
        for idx, value in enumerate(header)
        if value and (re.fullmatch(r"20[0-9]{2}", value) or "–" in value or "-" in value)
    }
    values: dict[int, dict[str, float]] = {}
    for row in rows:
        label = _clean(row[0] if row else "").lower()
        if label not in {"3-month treasury bills", "10-year treasury notes"}:
            continue
        key = "cbo_3m_pct" if label.startswith("3-month") else "cbo_10y_pct"
        for col_idx, year_label in year_cols.items():
            if col_idx >= len(row) or not row[col_idx]:
                continue
            years = _expand_year_label(year_label)
            for year in years:
                values.setdefault(year, {})[key] = _safe_float(row[col_idx])
    return values


def _year_cols(rows: list[list[str]]) -> dict[int, str]:
    for row in rows:
        years = {
            idx: _clean(value)
            for idx, value in enumerate(row)
            if re.fullmatch(r"20[0-9]{2}", _clean(value))
        }
        if "2026" in years.values() and "2036" in years.values():
            return years
    return {}


def _expand_year_label(label: str) -> list[int]:
    label = _clean(label).replace(" ", "")
    if re.fullmatch(r"20[0-9]{2}", label):
        return [int(label)]
    match = re.fullmatch(r"(20[0-9]{2})[–-](20[0-9]{2})", label)
    if match:
        return list(range(int(match.group(1)), int(match.group(2)) + 1))
    return []


def _federal_fiscal_year_calendar_quarters(year: int) -> list[str]:
    return [f"{year - 1}Q4", f"{year}Q1", f"{year}Q2", f"{year}Q3"]


def build_primary_flow_path(output_path: Path, *, cbo_budget_path: Path, scenario_ids: list[str]) -> tuple[pd.DataFrame, dict]:
    values = _cbo_budget_values(cbo_budget_path)
    rows: list[dict] = []
    for year, metrics in sorted(values.items()):
        if year < 2026:
            continue
        deficit_magnitude = -metrics.get("deficit_bil", 0.0)
        net_interest = metrics.get("net_interest_bil", 0.0)
        primary_deficit = deficit_magnitude - net_interest
        for quarter in _federal_fiscal_year_calendar_quarters(year):
            for scenario_id in scenario_ids:
                rows.append(
                    {
                        "scenario_id": scenario_id,
                        "quarter": quarter,
                        "primary_fiscal_flow_to_du_bil": f"{primary_deficit / 4.0:.12f}",
                        "non_debt_outlays_to_du_bil": "",
                        "receipts_from_du_bil": "",
                        "primary_flow_status": "aggregate_cash_proxy_from_cbo_total_deficit_less_net_interest",
                        "aggregate_primary_deficit_bil": f"{primary_deficit:.12f}",
                        "du_primary_flow_share_assumption": "1.0",
                        "recipient_mapping_status": "recipient_mapping_unavailable_aggregate_proxy",
                        "assumption_mode": "true",
                        "central_default_eligible": "true",
                        "source_family": "cbo_budget_projection",
                        "source_key": "51118-2026-02-Budget-Projections.xlsx:Table 1-1",
                        "source_status": "source_backed_federal_fiscal_year_mapped_to_calendar_quarters_aggregate_primary_deficit_proxy_not_recipient_mapped",
                        "claim_boundary": RATEWALL_CLAIM_BOUNDARY,
                    }
                )
    frame = pd.DataFrame(rows)
    frame.to_csv(output_path, index=False)
    return frame, {
        "cbo_budget_path": str(cbo_budget_path),
        "fiscal_year_calendar_mapping": "federal_fy_y_to_calendar_y_minus_1_q4_through_y_q3",
        "rows": len(frame),
    }


def _latest_treasury_curve() -> tuple[str, dict[float, float]]:
    bodies = []
    now = pd.Timestamp.now(tz="UTC")
    for offset in range(0, 8):
        month = now - pd.DateOffset(months=offset)
        url = f"{TREASURY_CURVE_XML}&field_tdr_date_value_month={month.strftime('%Y%m')}"
        with urlopen(Request(url, headers={"User-Agent": "Mozilla/5.0"}), timeout=60) as response:
            body = response.read().decode("utf-8", errors="replace")
        bodies.append(body)
        if "BC_10YEAR" in body:
            break
    body = "\n".join(bodies)
    root = ET.fromstring(body)
    tenor_map = {
        "BC_3MONTH": 0.25,
        "BC_6MONTH": 0.5,
        "BC_1YEAR": 1.0,
        "BC_2YEAR": 2.0,
        "BC_5YEAR": 5.0,
        "BC_10YEAR": 10.0,
        "BC_20YEAR": 20.0,
        "BC_30YEAR": 30.0,
    }
    latest_date = ""
    latest_rates: dict[float, float] = {}
    for entry in root.findall(".//{http://www.w3.org/2005/Atom}entry"):
        props = None
        for node in entry.iter():
            if node.tag.endswith("properties"):
                props = node
                break
        if props is None:
            continue
        values = {child.tag.split("}")[-1]: child.text for child in list(props)}
        date_text = str(values.get("NEW_DATE", ""))[:10]
        if date_text <= latest_date:
            continue
        rates = {
            tenor: _safe_float(values.get(field)) / 100.0
            for field, tenor in tenor_map.items()
            if values.get(field) not in {None, ""}
        }
        if rates:
            latest_date = date_text
            latest_rates = rates
    if not latest_rates:
        raise ValueError("Treasury yield curve XML did not contain rate rows.")
    return latest_date, latest_rates


def _interp_rate(curve: dict[float, float], tenor: float) -> float:
    if tenor in curve:
        return curve[tenor]
    points = sorted(curve)
    if tenor <= points[0]:
        return curve[points[0]]
    if tenor >= points[-1]:
        return curve[points[-1]]
    for left, right in zip(points, points[1:]):
        if left <= tenor <= right:
            weight = (tenor - left) / (right - left)
            return curve[left] + weight * (curve[right] - curve[left])
    return curve[points[-1]]


def _shape_preserving_curve(base_curve: dict[float, float], *, cbo_3m: float, cbo_10y: float) -> dict[float, float]:
    base_3m = _interp_rate(base_curve, 0.25)
    base_10y = _interp_rate(base_curve, 10.0)
    short_shift = cbo_3m - base_3m
    long_shift = cbo_10y - base_10y
    out: dict[float, float] = {}
    for tenor in TENORS:
        if tenor <= 1.0:
            shift = short_shift
        elif tenor >= 10.0:
            shift = long_shift
        else:
            shift = short_shift + (long_shift - short_shift) * ((tenor - 1.0) / 9.0)
        out[tenor] = max(0.0, _interp_rate(base_curve, tenor) + shift)
    return out


def build_yield_curve_surface(output_path: Path, *, cbo_economic_path: Path) -> tuple[pd.DataFrame, dict]:
    current_date, current_curve = _latest_treasury_curve()
    cbo_rates = _cbo_rate_values(cbo_economic_path)
    rows: list[dict] = []
    for scenario_id, scenario in RATE_SCENARIOS.items():
        for year, rates in sorted(cbo_rates.items()):
            if year < 2026:
                continue
            curve = _shape_preserving_curve(
                current_curve,
                cbo_3m=rates["cbo_3m_pct"] / 100.0
                + float(scenario["short_shift"]),
                cbo_10y=rates["cbo_10y_pct"] / 100.0
                + float(scenario["long_shift"]),
            )
            for quarter_idx in range(1, 5):
                curve_date = pd.Timestamp(year=year, month=(quarter_idx - 1) * 3 + 1, day=1).date().isoformat()
                for tenor, rate in curve.items():
                    rows.append(
                        {
                            "scenario_id": scenario_id,
                            "curve_date": curve_date,
                            "tenor_years": f"{tenor:.2f}",
                            "nominal_rate": f"{rate:.12f}",
                            "rate_type": "nominal",
                            "curve_basis": "treasury_par_shape_preserving_cbo_3m_10y_anchor",
                            "source_family": "treasury_daily_yield_curve;cbo_economic_projection",
                            "source_key": f"{current_date};51135-2026-02-Economic-Projections.xlsx:Table 2-1",
                            "interpolation_method": (
                                "current_curve_shape_shifted_to_cbo_3m_10y_annual_anchors;"
                                f"short_shift={scenario['short_shift']};"
                                f"long_shift={scenario['long_shift']}"
                            ),
                            "central_default_eligible": str(
                                scenario["central_default_eligible"]
                            ),
                            "sensitivity_only": str(scenario["sensitivity_only"]),
                            "source_status": str(scenario["source_status"]),
                            "claim_boundary": RATEWALL_CLAIM_BOUNDARY,
                        }
                    )
    frame = pd.DataFrame(rows)
    frame.to_csv(output_path, index=False)
    return frame, {"treasury_curve_date": current_date, "rows": len(frame)}


def build_holder_absorption_path(
    output_path: Path,
    *,
    tdcmix_prior_path: Path,
    z1_absorption_path: Path,
    bills_primary_path: Path,
    coupons_primary_path: Path,
    holder_absorption_calibration: dict[str, float | list[float]] | None = None,
) -> tuple[pd.DataFrame, dict]:
    scenarios, metadata = _load_absorption_scenarios(
        tdcmix_prior_path,
        z1_absorption_path=z1_absorption_path,
        bills_primary_path=bills_primary_path,
        coupons_primary_path=coupons_primary_path,
        holder_absorption_calibration=holder_absorption_calibration,
    )
    rows: list[dict] = []
    for scenario_id, category_shares in scenarios.items():
        for year in range(2026, 2037):
            for quarter_idx in range(1, 5):
                quarter = f"{year}Q{quarter_idx}"
                for holder in TDCSIM_HOLDERS:
                    rows.append(
                        {
                            "scenario_id": scenario_id,
                            "quarter": quarter,
                            "holder_type": holder,
                            "bills_pct": f"{category_shares['bills'].get(holder, 0.0):.12f}",
                            "notes_pct": f"{category_shares['notes'].get(holder, 0.0):.12f}",
                            "bonds_pct": f"{category_shares['bonds'].get(holder, 0.0):.12f}",
                            "tips_pct": f"{category_shares['tips'].get(holder, 0.0):.12f}",
                            "frn_pct": f"{category_shares['frn'].get(holder, 0.0):.12f}",
                            "nonmarketable_pct": "0.0",
                            "source_family": (
                                "tdcmix_holder_absorption_prior_contract;"
                                "tdcmix_z1_exact_recent_absorption;"
                                "tsyparty_primary_market_buyer_composition"
                            ),
                            "source_key": (
                                f"{tdcmix_prior_path.name};"
                                f"{z1_absorption_path.name};"
                                f"{bills_primary_path.name};"
                                f"{coupons_primary_path.name}"
                            ),
                            "source_status": (
                                "instrument_specific_holder_absorption_prior_not_holder_allocation_evidence;"
                                f"{metadata['dealer_bridge_mapping']}"
                                f";primary_market_overlay_{metadata['primary_market_overlay_coverage']}"
                                + (
                                    ";mmf_collapsed_into_du_current_private_bucket"
                                    if holder == "Private"
                                    else ""
                                )
                            ),
                            "mmf_collapsed_into_du": "true" if holder == "Private" else "false",
                            "central_default_eligible": (
                                "true" if scenario_id == "current_mix_baseline" else "false"
                            ),
                            "sensitivity_only": (
                                "false" if scenario_id == "current_mix_baseline" else "true"
                            ),
                            "blocked_unmapped_share": "0.0",
                            "claim_boundary": RATEWALL_CLAIM_BOUNDARY,
                        }
                    )
    frame = pd.DataFrame(rows)
    frame.to_csv(output_path, index=False)
    return frame, {
        "tdcmix_prior_path": str(tdcmix_prior_path),
        "z1_absorption_path": str(z1_absorption_path),
        "bills_primary_path": str(bills_primary_path),
        "coupons_primary_path": str(coupons_primary_path),
        "rows": len(frame),
        **metadata,
    }


def build_interest_component_contract(output_path: Path) -> tuple[pd.DataFrame, dict]:
    rows = [
        ("coupon_interest", "true", "true", "false", "Fixed coupon and non-TIPS coupon cash paid to DU."),
        ("bill_discount_interest", "true", "true", "false", "Treasury bill discount separated from principal return."),
        ("frn_reset_interest", "true", "true", "false", "FRN coupon cash from benchmark reset plus spread."),
        ("tips_coupon_interest", "true", "true", "false", "TIPS coupon cash only."),
        ("tips_inflation_compensation", "false", "false", "true", "TIPS inflation compensation kept separate from default overlap."),
        ("principal_return", "false", "false", "false", "Principal redemption is TDC support, not direct-interest overlap."),
    ]
    frame = pd.DataFrame(
        [
            {
                "cash_component_key": key,
                "enters_tdc_interest_to_du": enters_tdc,
                "enters_direct_interest_overlap_default": overlap,
                "separate_review_required": review,
                "component_note": note,
                "source_family": "tdcsim_ratewall_interest_component_contract",
                "source_status": "contract_boundary_not_empirical_estimate",
                "claim_boundary": RATEWALL_CLAIM_BOUNDARY,
            }
            for key, enters_tdc, overlap, review, note in rows
        ]
    )
    frame.to_csv(output_path, index=False)
    return frame, {"rows": len(frame)}


def build_ratewall_config(
    output_path: Path,
    *,
    input_dir: Path,
    contract_output_dir: Path,
    holder_absorption_calibration: dict[str, float | list[float]] | None = None,
) -> None:
    calibration = holder_absorption_calibration or _default_holder_absorption_calibration()
    base_curve = {
        "use_static": True,
        "years": TENORS,
        "rates": [0.04, 0.04, 0.04, 0.04, 0.042, 0.043, 0.045, 0.046],
    }
    issuance_profile = {
        "bills": {"category_cutoff_years": 1.0, "target_percentage_of_remainder": 0.22, "maturities": [0.25, 0.5, 1.0], "maturity_distribution": [0.40, 0.35, 0.25]},
        "notes": {"category_cutoff_years": 10.0, "target_percentage_of_remainder": 0.58, "maturities": [2.0, 5.0, 10.0], "maturity_distribution": [0.35, 0.35, 0.30]},
        "bonds": {"category_cutoff_years": 999.0, "target_percentage_of_remainder": 0.20, "maturities": [20.0, 30.0], "maturity_distribution": [0.45, 0.55]},
        "TIPS": {"target_percentage": 0.06, "maturities": [5.0, 10.0, 30.0], "maturity_distribution": [0.40, 0.35, 0.25]},
        "FRN": {"target_percentage": 0.04, "maturities": [2.0], "maturity_distribution": [1.0]},
        "remainder_maturity_years": 0.5,
    }
    base_prefs = {
        holder: {
            f"{category}_pct": (1.0 / len(TDCSIM_HOLDERS))
            for category in ["bills", "notes", "bonds", "tips", "frn"]
        }
        for holder in TDCSIM_HOLDERS
    }
    scenario_rows = [
        {
            "name": scenario_id,
            "overrides": {
                "yield_curve_surface": {
                    "file": str(
                        (input_dir / "tdcsim_yield_curve_surface.csv").relative_to(
                            output_path.parent
                        )
                    ),
                    "scenario_id": curve_id,
                }
            },
        }
        for scenario_id, curve_id in SCENARIO_CURVE_MAP.items()
    ]
    config = {
        "simulation_period": {"start_date": "2026-04-30", "end_date": "2036-12-31", "frequency": "W", "enable_preference_trading": False, "coarse_frequency_action": "warn"},
        "initial_values": {"reserves": 2500.0, "tdc_level": 0.0, "tga": 750.0},
        "initial_portfolio": {"mode": "file", "file": str((input_dir / "tdcsim_initial_portfolio_cohorts.csv").relative_to(output_path.parent))},
        "tga_params": {"target_balance": 750.0, "floor": 100.0},
        "fiscal_params": {"initial_weekly_spending": 0.0, "initial_weekly_taxes": 0.0, "spending_growth_qtr": 0.0, "tax_growth_qtr": 0.0},
        "treasury_issuance_profile": issuance_profile,
        "yield_curve": base_curve,
        "yield_curve_surface": {"file": str((input_dir / "tdcsim_yield_curve_surface.csv").relative_to(output_path.parent)), "scenario_id": "cbo_shape_preserving_baseline"},
        "sector_preferences": base_prefs,
        "auction_absorption_preferences": base_prefs,
        "secondary_target_preferences": base_prefs,
        "ratewall_input_paths": {
            "primary_flow_to_du_file": str((input_dir / "tdcsim_primary_flow_to_du_path.csv").relative_to(output_path.parent)),
            "holder_absorption_path_file": str((input_dir / "tdcsim_holder_absorption_path.csv").relative_to(output_path.parent)),
        },
        "holder_absorption_calibration": calibration,
        "tips_params": {"cpi_start_level": 100.0, "cpi_annual_inflation": 0.02, "ref_cpi_lag_months": 3, "default_real_coupon_rate": 0.005},
        "frn_params": {"benchmark_maturity_years": 0.25, "default_fixed_spread": 0.0005},
        "nonmarketable_params": {"interest_rate_basis_maturities": [5.0, 10.0], "interest_crediting_frequency": "semi-annual", "initial_holder": "TrustFunds", "rate_setting_method": "yield_curve_points"},
        "other_flows": {"reserve_transfer": 0.0, "cb_net_expense": 0.0, "money_minting_transfers": 0.0},
        "rate_sensitive_demand": {"enabled": False, "min_multiplier": 0.25, "anchor_maturity_years": 5.0, "slope_short_maturity_years": 2.0, "slope_long_maturity_years": 10.0, "auction": {}, "secondary": {}},
        "financing_cost_options": {"include_tips_inflation_accretion": False},
        "ratewall_contract": {
            "enabled": True,
            "output_dir": str(contract_output_dir.relative_to(output_path.parent)),
            "input_manifest": str((input_dir / "tdcsim_ratewall_input_manifest.json").relative_to(output_path.parent)),
            "private_route_sensitivity_file": "../tdcest/data/processed/tdc_tdcsim_private_route_allocation_sensitivity.csv",
        },
        "parallel_execution": {
            "group_workers": "auto",
            "note": "Override with TDCSIM_GROUP_WORKERS for independent scenario groups.",
        },
        "scenario_parallel_workers": "auto",
        "scenario_groups": [
            {
                "group_name": "RateWall Source Backed TDC Forward",
                "group_output_settings": {"save_results_csv": True, "save_results_filename": "output/ratewall_source_backed_tdc", "output_mode": "single_file", "graphs_to_show": []},
                "scenarios": scenario_rows,
            }
        ],
    }
    output_path.write_text(yaml.safe_dump(config, sort_keys=False), encoding="utf-8")


def build_all(
    *,
    output_dir: Path,
    config_path: Path,
    ratewall_root: Path,
    project_root: Path,
) -> dict:
    _ensure_dir(output_dir)
    contract_output_dir = project_root / "output" / "ratewall_contract_source_backed"
    tsyparty_z1_path = ratewall_root.parent / "tsyparty" / "data" / "interim" / "z1_holdings_wide.csv"
    tdcmix_prior_path = ratewall_root.parent / "tdcmix" / "data" / "processed" / "holder_absorption_prior_contract.csv"
    z1_absorption_path = ratewall_root.parent / "tdcmix" / "data" / "processed" / "z1_exact_holder_absorption_panel.csv"
    bills_primary_path = ratewall_root.parent / "tsyparty" / "data" / "interim" / "bills_quarterly_composition.csv"
    coupons_primary_path = ratewall_root.parent / "tsyparty" / "data" / "interim" / "nominal_coupons_quarterly_composition.csv"
    cbo_budget_path = ratewall_root / "data" / "raw" / "cbo" / "51118-2026-02-Budget-Projections.xlsx"
    cbo_economic_path = ratewall_root / "data" / "raw" / "cbo" / "51135-2026-02-Economic-Projections.xlsx"
    scenario_ids = list(SCENARIO_CURVE_MAP)
    holder_absorption_calibration = _load_holder_absorption_calibration(config_path)

    artifacts = {}
    _, artifacts["initial_portfolio"] = build_initial_portfolio(
        output_dir / "tdcsim_initial_portfolio_cohorts.csv",
        tsyparty_z1_path=tsyparty_z1_path,
    )
    _, artifacts["primary_flow"] = build_primary_flow_path(
        output_dir / "tdcsim_primary_flow_to_du_path.csv",
        cbo_budget_path=cbo_budget_path,
        scenario_ids=scenario_ids,
    )
    _, artifacts["yield_curve"] = build_yield_curve_surface(
        output_dir / "tdcsim_yield_curve_surface.csv",
        cbo_economic_path=cbo_economic_path,
    )
    _, artifacts["holder_absorption"] = build_holder_absorption_path(
        output_dir / "tdcsim_holder_absorption_path.csv",
        tdcmix_prior_path=tdcmix_prior_path,
        z1_absorption_path=z1_absorption_path,
        bills_primary_path=bills_primary_path,
        coupons_primary_path=coupons_primary_path,
        holder_absorption_calibration=holder_absorption_calibration,
    )
    _, artifacts["interest_component"] = build_interest_component_contract(
        output_dir / "tdcsim_interest_component_contract.csv"
    )
    build_ratewall_config(
        config_path,
        input_dir=output_dir,
        contract_output_dir=contract_output_dir,
        holder_absorption_calibration=holder_absorption_calibration,
    )

    files = sorted(output_dir.glob("*.csv")) + [config_path]
    manifest = {
        "schema_version": "0.1.0",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "claim_boundary": RATEWALL_CLAIM_BOUNDARY,
        "artifacts": artifacts,
        "files": {path.name: {"sha256": _sha256(path), "bytes": path.stat().st_size} for path in files},
        "source_hierarchy": {
            "bond_history": "FiscalData MSPD security cohorts scaled to MSPD Table 1 class totals plus public aggregate holder constraints",
            "yield_curve": "Treasury daily par curve shape shifted to CBO 3-month and 10-year projected anchors",
            "primary_flow": "CBO total deficit less net interest as aggregate cash proxy",
            "holder_absorption": (
                "instrument-specific holder absorption priors from tdcmix, "
                "recent z1 exact absorption, and tsyparty primary-market "
                "buyer composition; not holder-allocation evidence"
            ),
        },
    }
    manifest_path = output_dir / "tdcsim_ratewall_input_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description="Build source-backed tdcsim inputs for RateWall.")
    parser.add_argument("--output-dir", default="data/ratewall_inputs")
    parser.add_argument("--config-path", default="tdc_config_ratewall_source_backed.yaml")
    parser.add_argument("--ratewall-root", default="../ratewall")
    args = parser.parse_args()
    project_root = Path(__file__).resolve().parents[1]
    manifest = build_all(
        output_dir=(project_root / args.output_dir).resolve(),
        config_path=(project_root / args.config_path).resolve(),
        ratewall_root=(project_root / args.ratewall_root).resolve(),
        project_root=project_root,
    )
    print(json.dumps({"status": "ok", "files": manifest["files"]}, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
